In [1]:
import numpy as np

In [2]:
# create array , matrix

a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
# shape
print(a.shape, b.shape)

(4,) (2, 2)


In [6]:
# reshape
c = a.reshape((4, 1))
c.shape

(4, 1)

In [8]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [10]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
c

array([ 4, 10, 18])

In [12]:
c = np.array([10])

d = a + c
d

array([11, 12, 13])

In [13]:
e = a + 5
e

array([6, 7, 8])

In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [17]:
b = a[2:7:2]
b

array([3, 5, 7])

In [18]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
sun_a = np.sum(a)
sun_a

36

In [21]:
max_a = np.max(a)
max_a

8

In [22]:
min_a = np.min(a)
min_a

1

In [23]:
a = np.array([4, 2, 9, 6, 7, 3, 5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [25]:
a = np.random.randint(0, 100, (3, 4))
a

array([[81, 95, 36,  9],
       [73, 48, 16, 56],
       [78, 74, 35, 82]])

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [28]:
c.shape

(6,)

In [30]:
a

array([1, 2, 3])

In [29]:
# normalize
mean_a = np.mean(a)
mean_a

2.0

In [31]:
std_a = np.std(a)
std_a

0.816496580927726

In [32]:
norm_a = (a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [34]:
np.mean(norm_a)

0.0

In [35]:
np.std(norm_a)

0.9999999999999999